# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name:'Star Wars' }, { name:'Lord of the Rings' }])
#   Character.create(name:'Luke', movie: movies.first)


Category.create(category_id: 1, category_initials:'S1', question:"I have sometimes wished I were a boy.")
Category.create(category_id: 1, category_initials:'S2', question:"I have always been somewhat tomboyish.")
Category.create(category_id: 1, category_initials:'S3', question:"I rarely wear makeup or don"+"'t really like to.")
Category.create(category_id: 1, category_initials:'S4', question:"As a child I never played with "+"'girl toys"+"' like dolls, kitchen toys, toy prams etc.")
Category.create(category_id: 1, category_initials:'S5', question:"I have never really liked wearing dresses or female clothing in general.")
Category.create(category_id: 1, category_initials:'S6', question:"I"+"'ve always been attracted to girlie girls, I am more boyish.")
Category.create(category_id: 1, category_initials:'S7', question:"I mostly gravitate to boys as friends rather than boyfriend material.")
Category.create(category_id: 1, category_initials:'S8', question:"Girls have openly shown interest in me or assumed I was gay.")
Category.create(category_id: 1, category_initials:'S9', question:"Even at an early age when playing house with other girls, I always wanted to be the daddy.")
Category.create(category_id: 1, category_initials:'S10', question:"Looking back, I"+"'ve always been obsessed with certain girls.")
Category.create(category_id: 1, category_initials:'S12', question:"As far as I remember, I have only really been attracted to girls.")

Category.create(category_id: 2, category_initials:'S1', question:"I don"+"'t think of myself as particularly feminine.")
Category.create(category_id: 2, category_initials:'S2', question:"I have always enjoyed rough and tumble play with the boys, boy interests etc.")
Category.create(category_id: 2, category_initials:'S3', question:"I"+"'m not a make up kind of girl.")
Category.create(category_id: 2, category_initials:'S4', question:"As a child I played with trucks, cars, guns, toy tool sets like or other "+"'boy toys"+"'.")
Category.create(category_id: 2, category_initials:'S5', question:"I have generally preferred guy"+"'s clothing to girl"+"'s.")
Category.create(category_id: 2, category_initials:'S6', question:"I have always thought I wasn"+"'t all that girlie and thought girlie girls were very attractive.")
Category.create(category_id: 2, category_initials:'S7', question:"Even at an early age, I never really had boy crushes.")
Category.create(category_id: 2, category_initials:'S8', question:"People have asked me if I was gay.")
Category.create(category_id: 2, category_initials:'S9', question:"I remember at a young age thinking two female dolls(like barbie & barbie) could be together.")
Category.create(category_id: 2, category_initials:'S10', question:"I have always had bad crushes on some close female friends.")
Category.create(category_id: 2, category_initials:'S11', question:"I was never really boy crazy like other girls.")
Category.create(category_id: 2, category_initials:'S12', question:"I have never felt any attraction for boys, I have always only liked girls.")

Category.create(category_id: 1, category_initials:'C1', question:"I am drawn to girls with a boyish "+'look'+" about them.")
Category.create(category_id: 1, category_initials:'C2', question:"I have noticed a girl and wondered if she was gay.")
Category.create(category_id: 1, category_initials:'C3', question:"I remember seeing two girls kissing on a TV show, and being really curious.")
Category.create(category_id: 1, category_initials:'C4', question:"I enjoy reading lesbian fiction, non fiction, fan fiction, novels or smut material.")
Category.create(category_id: 1, category_initials:'C5', question:"I have registered on a lesbian dating app to talk with girls.")
Category.create(category_id: 1, category_initials:'C6', question:"I"+"'ve mostly found effeminate boys more attractive than boys that are more masculine.")
Category.create(category_id: 1, category_initials:'C7', question:"I have rented(or wanted to rent) a lesbian adult film.")
Category.create(category_id: 1, category_initials:'C8', question:"I have thought a certain (female) artist/celeb was hot and wondered if she was into girls.")
Category.create(category_id: 1, category_initials:'C9', question:"I have gone a time or two to a lesbian bar, pub, or event.")
Category.create(category_id: 1, category_initials:'C10', question:"I have wondered what two women do in bed, and how that would feel.")
Category.create(category_id: 1, category_initials:'C11', question:"I have quite a few LGBTQIA friends.")

Category.create(category_id: 2, category_initials:'C1', question:"I have always been a bit curious about tomboyish girls.")
Category.create(category_id: 2, category_initials:'C2', question:"I think I can tell when a girl is gay.")
Category.create(category_id: 2, category_initials:'C3', question:"I"+"'ve seen two girls make out at a night out and was really drawn to them.")
Category.create(category_id: 2, category_initials:'C4', question:"I"+"'ve wondered where I could find or read lesbian novels or fan fiction.")
Category.create(category_id: 2, category_initials:'C5', question:"I have downloaded a lesbian app,  but just couldn"+"'t get myself to use it.")
Category.create(category_id: 2, category_initials:'C6', question:"I think certain very groomed male celebs, who look a bit effeminate are sexy.")
Category.create(category_id: 2, category_initials:'C7', question:"I have wondered what two girls do together sexually.")
Category.create(category_id: 2, category_initials:'C8', question:"I have noticed an artist/celeb and thought I think she might be into girls.")
Category.create(category_id: 2, category_initials:'C9', question:"I have joined a sports team,hoping to meet lesbians there.")
Category.create(category_id: 2, category_initials:'C10', question:"I have considered what it would be like to sleep with a girl.")
Category.create(category_id: 2, category_initials:'C11', question:"In my circle of friends I regularly hang out with quite a few are LGBTQIA.")

Category.create(category_id: 1, category_initials:'A1',question:"My first sexual experience was with a girl.")
Category.create(category_id: 1, category_initials:'A2',question:"I sometimes fantasize about making out with a girl.")
Category.create(category_id: 1, category_initials:'A3',question:"When I masturbate, I sometimes picture a girl.")
Category.create(category_id: 1, category_initials:'A4',question:"I have had erotic dreams about being with a girl.")
Category.create(category_id: 1, category_initials:'A5',question:"I sometimes picture myself being with a girl  - making out, cuddling, touching etc.")
Category.create(category_id: 1, category_initials:'A6',question:"I"+"'ve always had an uncomfortable feeling, a bit of shyness around certain pretty girls.")
Category.create(category_id: 1, category_initials:'A7',question:"I have had one or more girl crushes since 1st grade.")
Category.create(category_id: 1, category_initials:'A8',question:"I have considered the idea of wanting to marry a girl.")
Category.create(category_id: 1, category_initials:'A9',question:"Although I"+"'ve only dated guys, I"+"'ve often found certain girls really attractive.")
Category.create(category_id: 1, category_initials:'A10',question:"I get turned on by lesbian sexual content, and girlie parts(boobs, bum, etc).")
Category.create(category_id: 1, category_initials:'A11',question:"I find adult or erotic magazines with nude women sexually arousing.")
Category.create(category_id: 1, category_initials:'A12',question:"I have found myself looking at a girl, thinking "+"'she"+"'s the most beautiful girl I know"+"'.")
Category.create(category_id: 1, category_initials:'A13',question:"I enjoy chatting with a girl on a lesbian dating app; I think she"+"'s cute, funny, sexy..")
Category.create(category_id: 1, category_initials:'A14',question:"I"+"'ve seen a girl and thought, damn she"+"'s sexy, she"+"'s really got (a) sexy ****!")
Category.create(category_id: 1, category_initials:'A15',question:"I have been drawn to a beautiful girl on a night out, and wanted to dance with her.")
Category.create(category_id: 1, category_initials:'A16',question:"I enjoy making out with hot girls.")
Category.create(category_id: 1, category_initials:'A17',question:"I find some girls really sexy.")

Category.create(category_id: 2, category_initials:'A1',question:"My first kiss was with this girl.")
Category.create(category_id: 2, category_initials:'A2',question:"I have sometimes wondered how kissing a girl would feel like.")
Category.create(category_id: 2, category_initials:'A3',question:"When pleasuring myself, I get turned on when I imagine a girl.")
Category.create(category_id: 2, category_initials:'A4',question:"I have had erotic dreams having sex with a girl.")
Category.create(category_id: 2, category_initials:'A5',question:"I have imagined being close to this girl - making out, touching, cuddling etc.")
Category.create(category_id: 2, category_initials:'A6',question:"I can"+"'t seem to have a (female) friend, as I"+"'m so tense around girls I like.")
Category.create(category_id: 2, category_initials:'A7',question:"I remember staring at a class mate, thinking she"+"'s really cute or adorable.")
Category.create(category_id: 2, category_initials:'A8',question:"I have wondered what it would be like if I married a (female) friend of mine.")
Category.create(category_id: 2, category_initials:'A9',question:"I have been with giuys, but I"+"'ve always felt something special for certain girls.")
Category.create(category_id: 2, category_initials:'A10',question:"I find lesbian sexual material hot.")
Category.create(category_id: 2, category_initials:'A11',question:"I find the female body very sexually attractive or arousing.")
Category.create(category_id: 2, category_initials:'A12',question:"There was a girl I found very attractive, she was basically perfect.")
Category.create(category_id: 2, category_initials:'A13',question:"I sometimes find myself on a lesbian chat app chatting with a girl.")
Category.create(category_id: 2, category_initials:'A14',question:"I have noticed this attractive girl and thought "+"'hmm she"+"'s really hot.."+"'")
Category.create(category_id: 2, category_initials:'A15',question:"I have noticed an attrative girl on a night out, thinking I"+"'d like to know her.")
Category.create(category_id: 2, category_initials:'A16',question:"I have made out with girls and got tuned on.")
Category.create(category_id: 2, category_initials:'A17',question:"I have been very attracted to certain girls.")

Category.create(category_id: 1, category_initials:'SP1',question:"I"+"'ve felt a special feeling for certain girls, deep down I know it"+"'s not just friendship.")
Category.create(category_id: 1, category_initials:'SP2',question:"I have felt so connected to a girl, a sense of completeness when I"+"'m with her.")
Category.create(category_id: 1, category_initials:'SP3',question:"I have felt almost empty when this (female) friend isn"+"'t around.")
Category.create(category_id: 1, category_initials:'SP4',question:"I have had very strong feelings for a girl, maybe I loved her.")
Category.create(category_id: 1, category_initials:'SP5',question:"I"+"'m currently with a boy, but if I could I"+"'d rather be with a girl.")
Category.create(category_id: 1, category_initials:'SP6',question:"I"+"'ve wished I could be free someday to choose to form a family with a girl.")
Category.create(category_id: 1, category_initials:'SP7',question:"I have spent time with a girl, looking in her eyes, thinking how amazing she is.")
Category.create(category_id: 1, category_initials:'SP8',question:"I find myself thinking how amazing it feels cuddling with this (female) friend.")
Category.create(category_id: 1, category_initials:'SP9',question:"If being with a girl weren"+"'t an issue, my ideal partner would be this girl I know.")
Category.create(category_id: 1, category_initials:'SP10',question:"I have felt a bit shy and blushed around certain girls I thought were gorgeous.")
Category.create(category_id: 1, category_initials:'SP11',question:"I"+"'ve made out with a girl,and felt butterflies and all, but I"+"'d never tell her.")
Category.create(category_id: 1, category_initials:'SP12',question:"I"+"'ve had sex with a girl, but I"+"'m still into guys that doesn"+"'t make me gay.")
Category.create(category_id: 1, category_initials:'SP13',question:"I"+"'ve had strong feelings for a girl, but couldn"+"'t show it.")
Category.create(category_id: 1, category_initials:'SP14',question:"I have a boyfriend / husband, but I"+"'ve always liked girls.")
Category.create(category_id: 1, category_initials:'SP15',question:"I'll admit it some girls are hot, I"+"'d have sex with a girl if it weren"+"'t such an issue.")
Category.create(category_id: 1, category_initials:'SP16',question:"I"+"'ve always felt a strong attraction to girls that look a certain way.")
Category.create(category_id: 1, category_initials:'SP17',question:"I have lay in the arms of a girl feeling the safest I"+"'d ever felt.")
Category.create(category_id: 1, category_initials:'SP18',question:"I"+"'ve felt sexually aroused when I saw a naked girl.")
Category.create(category_id: 1, category_initials:'SP19',question:"I have slept with a girl and knew that wouldn"+"'t be my last time with a girl.")
Category.create(category_id: 1, category_initials:'SP20',question:"I"+"'ve sometimes felt like wanting to take care of/protect certain girls.")
Category.create(category_id: 1, category_initials:'SP21',question:"I"+"'ve been emotionally invested in certain female friendships appearing to be too clingy.")
Category.create(category_id: 1, category_initials:'SP22',question:"I remember missing a friend, missing her scent.")
Category.create(category_id: 1, category_initials:'SP23',question:"I"+"'ve have sometimes felt like wanting to be really close to a friend when hugging her.")
Category.create(category_id: 1, category_initials:'SP24',question:"I remember feeling my heart racing when my crush(a girl) spoke to me / looked at me.")
Category.create(category_id: 1, category_initials:'SP25',question:"I"+"'ve found myself thinking of a girl I liked, I just couldn"+"'t think of anything else.")
Category.create(category_id: 1, category_initials:'SP26',question:"I have sometimes felt self conscious around a girl I really liked.")
Category.create(category_id: 1, category_initials:'SP27',question:"There"+"'s this girl I liked so much, I would let her get away with anything.")

Category.create(category_id: 2, category_initials:'SP1',question:"I"+"'ve felt a very strong physical attraction for a girl I couldn"+"'t explain in words.")
Category.create(category_id: 2, category_initials:'SP2',question:"There"+"'s a friend I feel so close to, almost like we're soul mates.")
Category.create(category_id: 2, category_initials:'SP3',question:"I have felt almost ill when I had a fight with a girl I cared for.")
Category.create(category_id: 2, category_initials:'SP4',question:"I"+"'ve wondered why I have felt so deeply for a girl, almost like I was in love with her.")
Category.create(category_id: 2, category_initials:'SP5',question:"If things weren"+"'t so complicated, I would rather be with a girl.")
Category.create(category_id: 2, category_initials:'SP6',question:"I"+"'ve secretly wished two girls could form a family without people"+"'s judgement.")
Category.create(category_id: 2, category_initials:'SP7',question:"I remember staring into the eyes of a girl, thinking what a wonderful human she is.")
Category.create(category_id: 2, category_initials:'SP8',question:"I"+"'m often alone cuddling, touching, making out with a friend, I feel safe with her.")
Category.create(category_id: 2, category_initials:'SP9',question:"There"+"'s this friend who is my ideal partner, if only she were a guy.")
Category.create(category_id: 2, category_initials:'SP10',question:"Deep down I feel it"+"'s wrong to like a girl so much, but I can"+"'t help it.")
Category.create(category_id: 2, category_initials:'SP11',question:"I really enjoy making out with a girl I know, I get feelings, but we don"+"'t talk about it.")
Category.create(category_id: 2, category_initials:'SP12',question:"I"+"'ve had sex with a girl, but I like guys that doesn’t make me a lesbian.")
Category.create(category_id: 2, category_initials:'SP13',question:"I"+"'ve loved a girl, but kept those feelings hidden.")
Category.create(category_id: 2, category_initials:'SP14',question:"I"+"'m in a relationship with a guy, but I know I like girls.")
Category.create(category_id: 2, category_initials:'SP15',question:"I"+"'ve seen a girl and thought "+"'damn she"+"'s sexy, I"+"'d shag her if only .. "+"'")
Category.create(category_id: 2, category_initials:'SP16',question:"I"+"'m strongly attracted to certain type of girls.")
Category.create(category_id: 2, category_initials:'SP17',question:"It feels so good in the arms of this girl I really like.")
Category.create(category_id: 2, category_initials:'SP18',question:"I remember getting turned on when seeing a certain girl naked.")
Category.create(category_id: 2, category_initials:'SP19',question:"After my first sexual experience with a girl, I knew I"+"'d have to be with a girl one more time.")
Category.create(category_id: 2, category_initials:'SP20',question:"I"+"'ve sometimes felt a sense of protection for certain girls.")
Category.create(category_id: 2, category_initials:'SP21',question:"I"+"'ve been a bit jealous of this (female) friend spending time with other girls/guys.")
Category.create(category_id: 2, category_initials:'SP22',question:"I"+"'ve hugged a friend and thought how much I loved her scent.")
Category.create(category_id: 2, category_initials:'SP23',question:"When hugging a friend to comfort her, I"+"'ve wanted to feel her really close.")
Category.create(category_id: 2, category_initials:'SP24',question:"I"+"'ve felt all sort of amazing feelings, butterflies in the tummy when around certain girls.")
Category.create(category_id: 2, category_initials:'SP25',question:"I have liked a girl and literally couldn"+"'t get her off my mind.")
Category.create(category_id: 2, category_initials:'SP26',question:"I"+"'ve liked a girl and wanted her to really like me back.")
Category.create(category_id: 2, category_initials:'SP27',question:"There"+"'s a friend I care about, I have a bit of a soft for her.")

Category.create(category_id: 1, category_initials:'STR1',question:"I"+"'m certainly into guys.")
Category.create(category_id: 1, category_initials:'STR2',question:"I have sexual attractions or feelings for guys.")
Category.create(category_id: 1, category_initials:'STR3',question:"I have had a boy crush.")
Category.create(category_id: 1, category_initials:'STR4',question:"I have been or can see myself in a relationship with a guy.")
Category.create(category_id: 1, category_initials:'STR5',question:"I find guys sexually attractive.")
Category.create(category_id: 1, category_initials:'STR6',question:"I have fallen in love with a guy.")

Category.create(category_id: 1, category_initials:'AX1',question:"I have never had sexual attractions or feelings for anyone.")
Category.create(category_id: 1, category_initials:'AX2',question:"I have never had a crush or experienced love at first sight.")
Category.create(category_id: 1, category_initials:'AX3',question:"I can"+"'t see myself in a sexual relationship with anyone.")
Category.create(category_id: 1, category_initials:'AX4',question:"I have never felt sexual attraction for anyone.")
Category.create(category_id: 1, category_initials:'AX5',question:"I have never fallen in love.")
Category.create(category_id: 1, category_initials:'AX6',question:"I have never had sexual feelings for anyone.")
